### ISSUE TITLE
There is not enough horizontal space to show message lines

### ISSUE THREAD

**Issue by areguera** [CentOS/ansible-role-mailman#15]
Example of message with the problem:

![Screenshot from 2022-02-17 08-03-38](https://user-images.githubusercontent.com/5214519/154473811-44365a42-c2a5-4285-bb0c-ef06b7e14af1.png)

Example of message without the problem:

![Screenshot from 2022-02-17 08-04-03](https://user-images.githubusercontent.com/5214519/154473865-bf5e276c-9501-4802-bb1e-59a7c2d63bb7.png)

**Comment by areguera** [comment]
Tried a different layout at https://lists.dev.centos.org/pipermail/docs-sig/2022-February/000817.html, but the problem is still present when the content area is reduced. It seems to be the way `white-space: "pre-wrap"` works on the `pre` element. The newline at the end of lines is always preserved.

**Comment by zembtach** [comment]
This has been bother me for a while as well. Using this as an example: https://lists.centos.org/pipermail/centos-devel/2022-October/120628.html

This is what it looks like right now: [screenshot-1.png](https://user-images.githubusercontent.com/10890923/198899241-52504b59-bcb4-4843-971d-d0e9c1bbdab6.png)

The content is being affected by this style:
```css
/*!
* Mailing lists customization (https://gitlab.com/areguera/jekyll-theme-centos/)
* Copyright 2020-2021 Alain Reguera Delgado
* Licensed under MIT (https://gitlab.com/areguera/jekyll-theme-centos/-/blob/master/LICENSE)
*/
.aside__content__mailman__article pre {
 padding:0;
 overflow:hidden;
 max-height:none;
 border:none;
 background:#fff;
 font-size:1rem;
 white-space:pre-wrap
}
```
If I remove the `font-size` from that style, it falls back to the default `pre` in the stylesheet, which is this:
```css
pre {
 display:block;
 font-size:87.5%;
 color:#212529
}
```

That makes the font a bit smaller and the line wrapping looks nice: [screenshot-2.png](https://user-images.githubusercontent.com/10890923/198899337-a68e39f6-9e4b-46bb-a20a-e0877ad99cfa.png)
